# Generated by Django 5.0.14 on 2025-07-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='raw_llm_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
