# Generated by Django 5.0.14 on 2025-07-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_analysis_raw_llm_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='api_endpoint',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='api_key_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='scraping_method',
            field=models.CharField(choices=[('web', 'Web Scraping'), ('api', 'API'), ('both', 'Web Scraping and API')], default='web', max_length=10),
        ),
    ]
