# Generated by Django 5.0.14 on 2025-07-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_source_api_endpoint_source_api_key_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='request_params',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='request_type',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', max_length=10),
        ),
    ]
