# Generated by Django 5.0.14 on 2025-07-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_source_request_params_source_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
