# Generated by Django 5.0.14 on 2025-07-26 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_source_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_posts', to='core.source'),
        ),
        migrations.CreateModel(
            name='ApiResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_content', models.JSONField()),
                ('url', models.URLField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_responses', to='core.source')),
            ],
            options={
                'db_table': 'core_apiresponse',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='api_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.apiresponse'),
        ),
    ]
