# Generated by Django 4.2.7 on 2025-07-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_trading_config_and_enhanced_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingconfig',
            name='bot_enabled',
            field=models.BooleanField(default=True, help_text='Master switch to enable/disable all bot activities (scraping, analysis, trading)'),
        ),
        migrations.AlterField(
            model_name='source',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
