# Generated by Django 4.2.7 on 2025-07-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tradingconfig_bot_enabled_alter_source_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('new_post', 'New Post'), ('analysis_complete', 'Analysis Complete'), ('trade_executed', 'Trade Executed'), ('trade_closed', 'Trade Closed'), ('trade_close_requested', 'Trade Close Requested'), ('scraper_error', 'Scraper Error'), ('trade_status', 'Trade Status'), ('system_event', 'System Event')], max_length=50)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='core_activi_created_5c6490_idx'), models.Index(fields=['activity_type'], name='core_activi_activit_44a51a_idx')],
            },
        ),
    ]
