# Generated by Django 4.2.7 on 2025-07-31 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_activity_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='stop_loss_price_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='take_profit_price_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
