# Generated by Django 4.2.7 on 2025-08-01 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_enhanced_position_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='core.analysis'),
        ),
    ]
