# Generated by Django 4.2.7 on 2025-08-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_trade_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('pending_close', 'Open - Pending Close'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=15),
        ),
    ]
