# Generated by Django 5.0.6 on 2025-08-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_increase_post_url_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('new_post', 'New Post'), ('analysis_complete', 'Analysis Complete'), ('trade_executed', 'Trade Executed'), ('trade_closed', 'Trade Closed'), ('trade_close_requested', 'Trade Close Requested'), ('scraper_error', 'Scraper Error'), ('scraper_status', 'Scraper Status'), ('scraper_skipped', 'Scraper Skipped'), ('trade_status', 'Trade Status'), ('system_event', 'System Event')], max_length=50),
        ),
    ]
