# Generated by Django 5.0.6 on 2025-08-09 05:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_activitylog_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingconfig',
            name='max_concurrent_open_trades',
            field=models.IntegerField(default=5, help_text='Maximum number of trades that can be open (including pending/pending close) at the same time', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='tradingconfig',
            name='max_total_open_exposure',
            field=models.FloatField(default=5000.0, help_text='Maximum total dollar exposure across all open positions', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('new_post', 'New Post'), ('analysis_complete', 'Analysis Complete'), ('trade_executed', 'Trade Executed'), ('trade_closed', 'Trade Closed'), ('trade_close_requested', 'Trade Close Requested'), ('scraper_error', 'Scraper Error'), ('scraper_status', 'Scraper Status'), ('scraper_skipped', 'Scraper Skipped'), ('trade_status', 'Trade Status'), ('trade_rejected', 'Trade Rejected'), ('system_event', 'System Event')], max_length=50),
        ),
    ]
