# Generated by Django 5.0.6 on 2025-08-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_tradingconfig_max_concurrent_open_trades_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Master enable/disable for all outbound alerts')),
                ('bot_status_enabled', models.BooleanField(default=True, help_text='Send alert when bot is enabled/disabled')),
                ('order_open_enabled', models.BooleanField(default=True, help_text='Send alert when an order is opened (filled)')),
                ('order_close_enabled', models.BooleanField(default=True, help_text='Send alert when an order is closed')),
                ('trading_limit_enabled', models.BooleanField(default=True, help_text='Send alert when a trading limit is reached')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
