# Generated by Django 5.0.6 on 2025-08-09 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alertsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertsettings',
            name='heartbeat_enabled',
            field=models.BooleanField(default=False, help_text='Send periodic bot heartbeat while bot is enabled'),
        ),
        migrations.AddField(
            model_name='alertsettings',
            name='heartbeat_interval_minutes',
            field=models.IntegerField(default=30, help_text='Heartbeat interval in minutes (default 30)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)]),
        ),
        migrations.AddField(
            model_name='alertsettings',
            name='last_heartbeat_sent',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last heartbeat alert sent', null=True),
        ),
    ]
