# Generated by Django 5.0.6 on 2025-08-14 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_tradingconfig_bot_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingconfig',
            name='stop_loss_percentage',
            field=models.FloatField(default=2.0, help_text='Stop loss percentage (1.0 = 1%)', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(50.0)]),
        ),
    ]
