# Generated by Django 5.0.6 on 2025-08-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_tradingconfig_stop_loss_percentage"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="trade",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["open", "pending", "pending_close"])
                ),
                fields=("symbol",),
                name="unique_active_trade_per_symbol",
            ),
        ),
    ]
