# Generated by Django 5.0.6 on 2025-08-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_trackedcompany"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackedcompany",
            name="symbol",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
