# Generated by Django 5.0.6 on 2025-08-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_populate_trade_tracked_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertsettings",
            name="system_errors_enabled",
            field=models.BooleanField(
                default=True, help_text="Send alert when a system error occurs"
            ),
        ),
    ]
