# Generated by Django 5.0.6 on 2025-08-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_configcontrol"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="configcontrol",
            new_name="core_config_name_8a439d_idx",
            old_name="core_config_name_idx",
        ),
        migrations.AlterField(
            model_name="configcontrol",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
