# Generated by Django 5.0.6 on 2025-09-23 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_tradingconfig_max_position_size_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingconfig',
            name='intraday_close_minutes_before',
            field=models.IntegerField(default=30, help_text='Minutes before market close to start closing positions (intraday)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='tradingconfig',
            name='intraday_trading',
            field=models.BooleanField(default=False, help_text='If enabled, close all open positions shortly before market close'),
        ),
    ]
