# Generated by Django 5.0.6 on 2025-09-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_remove_time_limit_close_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="close_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("manual", "Manual Close"),
                    ("stop_loss", "Stop Loss"),
                    ("take_profit", "Take Profit"),
                    ("duplicate_sync", "Duplicate Sync"),
                    ("market_close", "Market Close"),
                    ("market_consensus_lost", "Market Consensus Lost"),
                    ("stale", "Stale - Time Limit Reached"),
                ],
                max_length=25,
                null=True,
            ),
        ),
    ]
