# Generated by Django 5.0.6 on 2025-09-28 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_alter_trade_close_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="enter_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysis",
            name="enter_confirmed",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysis",
            name="enter_price_change_n_pct",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysis",
            name="enter_volume_ratio",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tradingconfig",
            name="enter_confirm_window_minutes",
            field=models.IntegerField(
                default=5,
                help_text="N: Minutes after detection to measure confirmation window",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(120),
                ],
            ),
        ),
        migrations.AddField(
            model_name="tradingconfig",
            name="enter_confirmation_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Require price and volume confirmation before opening a position",
            ),
        ),
        migrations.AddField(
            model_name="tradingconfig",
            name="enter_price_change_threshold_pct",
            field=models.FloatField(
                default=0.2,
                help_text="Minimal signed price change threshold in % (e.g., 0.2 = 0.2%)",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="tradingconfig",
            name="enter_volume_ma_window",
            field=models.IntegerField(
                default=20,
                help_text="M: Moving-average window length for volume baseline (bars)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(200),
                ],
            ),
        ),
        migrations.AddField(
            model_name="tradingconfig",
            name="enter_volume_multiplier_threshold",
            field=models.FloatField(
                default=1.5,
                help_text="Required spike factor: volume_N / volume_MA",
                validators=[
                    django.core.validators.MinValueValidator(0.1),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
    ]
