# Generated by Django 5.0.6 on 2025-09-28 18:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_analysis_enter_checked_at_analysis_enter_confirmed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="freshness_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tradingconfig",
            name="freshness_decay_constant_min",
            field=models.FloatField(
                default=10.0,
                help_text="Decay constant in minutes for freshness exp(-delay/decay)",
                validators=[django.core.validators.MinValueValidator(0.1)],
            ),
        ),
        migrations.AddField(
            model_name="tradingconfig",
            name="freshness_threshold",
            field=models.FloatField(
                default=0.5,
                help_text="Minimum acceptable freshness value (0-1)",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
    ]
