# Generated by Django 5.0.6 on 2025-09-28 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_analysis_freshness_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingconfig",
            name="dynamic_exit_drawdown_tolerance_pct",
            field=models.FloatField(
                default=0.3,
                help_text="Max adverse move in % over N minutes to trigger dynamic exit (e.g., 0.3)",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
    ]
