# Generated by Django 5.0.6 on 2025-09-28 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_tradingconfig_dynamic_exit_drawdown_tolerance_pct"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingconfig",
            name="dynamic_exit_window_minutes",
            field=models.IntegerField(
                default=5,
                help_text="N: Rolling window in minutes for dynamic exit evaluation",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(120),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tradingconfig",
            name="enter_confirmation_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Require price and volume confirmation before opening a position",
            ),
        ),
    ]
