# Generated by Django 5.0.6 on 2025-09-28 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_tradingconfig_dynamic_exit_window_minutes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingconfig",
            name="profit_protect_threshold_pct",
            field=models.FloatField(
                default=0.7,
                help_text="Signed N-min price change to start profit protection (e.g., 0.7)",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="tradingconfig",
            name="profit_protect_trailing_distance_pct",
            field=models.FloatField(
                default=0.2,
                help_text="Tighter trailing stop distance in % once profit protection starts",
                validators=[
                    django.core.validators.MinValueValidator(0.01),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
    ]
