# Generated by Django 5.0.6 on 2025-09-28 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_tradingconfig_profit_protect_threshold_pct_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingconfig",
            name="profit_protect_window_minutes",
            field=models.IntegerField(
                default=5,
                help_text="N: Rolling window in minutes for profit-protect evaluation",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(120),
                ],
            ),
        ),
    ]
