# Generated by Django 5.0.6 on 2025-09-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_tradingconfig_profit_protect_window_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="correlation_id",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name="analysis",
            name="enter_status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("eligible", "Eligible"),
                    ("waiting_confirmation", "Waiting Confirmation"),
                    ("confirm_passed", "Confirmation Passed"),
                    ("confirm_failed", "Confirmation Failed"),
                    ("precheck_failed", "Pre-check Failed"),
                    ("scheduled_execution", "Scheduled Execution"),
                ],
                default="created",
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="TradeLifecycleEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject_type",
                    models.CharField(
                        choices=[("analysis", "Analysis"), ("trade", "Trade")],
                        max_length=16,
                    ),
                ),
                ("subject_id", models.IntegerField()),
                ("event_type", models.CharField(max_length=64)),
                ("prev_state", models.CharField(blank=True, max_length=64, null=True)),
                ("new_state", models.CharField(blank=True, max_length=64, null=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "correlation_id",
                    models.CharField(blank=True, max_length=36, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["subject_type", "subject_id", "created_at"],
                        name="core_tradel_subject_792adf_idx",
                    ),
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="core_tradel_event_t_088a6b_idx",
                    ),
                ],
            },
        ),
    ]
