# Generated by Django 5.0.6 on 2025-09-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_analysis_correlation_id_analysis_enter_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="enter_failure_code",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="analysis",
            name="enter_failure_detail",
            field=models.TextField(blank=True, null=True),
        ),
    ]
