# Generated by Django 5.0.6 on 2025-10-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_analysis_enter_failure_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="enter_volume_ma",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysis",
            name="enter_volume_n",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
