# Generated by Django 5.0.6 on 2025-10-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_analysis_enter_volume_ma_analysis_enter_volume_n"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="enter_window_minutes_snapshot",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysis",
            name="freshness_decay_min_snapshot",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysis",
            name="freshness_threshold_snapshot",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysis",
            name="price_threshold_pct_snapshot",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysis",
            name="profit_threshold_pct_snapshot",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysis",
            name="volume_multiplier_snapshot",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
