# Generated by Django 5.0.6 on 2025-10-01 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_analysis_enter_window_minutes_snapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_stale",
            field=models.BooleanField(
                default=False, help_text="Post is no longer eligible for trading"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="overnight",
            field=models.BooleanField(
                default=False, help_text="Post collected during market close"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="stale_reason",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="tradingconfig",
            name="overnight_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable overnight strategy (collect during close, act at open)",
            ),
        ),
        migrations.AddField(
            model_name="tradingconfig",
            name="overnight_reduce_sl_factor",
            field=models.FloatField(
                default=0.5,
                help_text="Factor to tighten stop loss at market open for overnight entries (0.5 = 50%)",
                validators=[
                    django.core.validators.MinValueValidator(0.1),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
    ]
