# Generated by Django 5.0.6 on 2025-10-01 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_post_is_stale_post_overnight_post_stale_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingconfig",
            name="overnight_max_age_hours",
            field=models.IntegerField(
                default=12,
                help_text="Maximum age in hours for overnight posts to be considered at open",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(48),
                ],
            ),
        ),
    ]
