# Generated by Django 5.0.6 on 2025-10-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_drop_autostart'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingconfig',
            name='autostart',
            field=models.BooleanField(default=False, help_text='Automatically enable bot during market hours and disable when closed'),
        ),
    ]
