# Generated by Django 5.0.6 on 2025-10-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_merge_0028_unique_symbol_and_0063_autostart'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trade',
            name='unique_active_trade_per_symbol_when_untracked',
        ),
        migrations.AlterField(
            model_name='tradingconfig',
            name='enter_confirmation_enabled',
            field=models.BooleanField(default=True, help_text='Require price OR volume confirmation (plus freshness) before opening a position'),
        ),
        migrations.AddConstraint(
            model_name='trade',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['open', 'pending', 'pending_close']), ('tracked_company__isnull', True)), fields=('symbol',), name='unique_active_trade_per_symbol_when_untracked'),
        ),
    ]
