"""
Django settings for news_trader project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-change-me-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 'yes', 'on')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,0.0.0.0,web').split(',')
CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",")

# Application definition
INSTALLED_APPS = [
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'rest_framework',
	'django_celery_beat',
	'telegram_bot',
	'core',
	'stats',
	'scraper',
	'trader',
]

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'whitenoise.middleware.WhiteNoiseMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'news_trader.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'news_trader.wsgi.application'

# Database configuration - supports both local and Docker setups
DATABASE_URL = os.getenv('DATABASE_URL')
if DATABASE_URL:
	# Parse DATABASE_URL for Docker/production
	import dj_database_url
	DATABASES = {
		'default': dj_database_url.parse(DATABASE_URL)
	}
else:
	# Default SQLite for development
	DATABASES = {
		'default': {
			'ENGINE': 'django.db.backends.sqlite3',
			'NAME': BASE_DIR / 'db.sqlite3',
		}
	}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
	BASE_DIR / 'static',
]

# Ensure staticfiles directory exists for Docker deployment
STATIC_ROOT.mkdir(exist_ok=True)

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Ensure media directory exists for Docker deployment  
MEDIA_ROOT.mkdir(exist_ok=True)

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Celery Configuration
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Sensible worker defaults (overridable by env)
CELERY_WORKER_CONCURRENCY = int(os.getenv('CELERY_CONCURRENCY', os.cpu_count() and max(1, min(2, os.cpu_count() // 2)) or 2))
CELERY_WORKER_MAX_TASKS_PER_CHILD = int(os.getenv('CELERY_MAX_TASKS_PER_CHILD', '100'))
CELERY_WORKER_MAX_MEMORY_PER_CHILD = int(os.getenv('CELERY_MAX_MEMORY_PER_CHILD', '300000'))
CELERY_TASK_TIME_LIMIT = int(os.getenv('CELERY_TASK_TIME_LIMIT', '180'))
CELERY_TASK_SOFT_TIME_LIMIT = int(os.getenv('CELERY_TASK_SOFT_TIME_LIMIT', '150'))

# API Keys from environment variables
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
ALPACA_API_KEY = os.getenv('ALPACA_API_KEY')
ALPACA_SECRET_KEY = os.getenv('ALPACA_SECRET_KEY')
ALPACA_BASE_URL = os.getenv('ALPACA_BASE_URL', 'https://paper-api.alpaca.markets')

# News API Keys
NEWSAPI_KEY = os.getenv('NEWSAPI_KEY')
ALPHAVANTAGE_API_KEY = os.getenv('ALPHAVANTAGE_API_KEY')
REDDIT_USER_AGENT = os.getenv('REDDIT_USER_AGENT', 'news-trader/1.0')

# LLM Server Root (for metrics tracking)
# Example: http://10.100.102.121:8000
LLM_ROOT_URL = os.getenv('LLM_ROOT_URL')

# Telegram Bot Configuration
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN')
TELEGRAM_AUTHORIZED_CHATS = os.getenv('TELEGRAM_AUTHORIZED_CHATS', os.getenv('TELEGRAM_CHAT_ID', ''))

# REST Framework
REST_FRAMEWORK = {
	'DEFAULT_PERMISSION_CLASSES': [
		'rest_framework.permissions.IsAuthenticated',
	],
	'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
	'PAGE_SIZE': 50
}

# Ensure logs directory exists for Docker deployment and determine file logging capability
LOGS_DIR = BASE_DIR / 'logs'

def _env_truthy(value: str) -> bool:
	return value.lower() in ('1', 'true', 'yes', 'on')

# Retention for rotating file handler
LOG_RETENTION_DAYS = int(os.getenv('LOG_RETENTION_DAYS', '14'))

# Decide if file logging is enabled and possible
_enable_file_logging_env = os.getenv('ENABLE_FILE_LOGGING', 'true')
_file_logging_enabled = _env_truthy(_enable_file_logging_env)
_can_write_log_file = False
_log_file_path = LOGS_DIR / 'django.log'

if _file_logging_enabled:
	try:
		LOGS_DIR.mkdir(parents=True, exist_ok=True)
		# Probe writability by touching the file
		with open(_log_file_path, 'a', encoding='utf-8'):
			pass
		_can_write_log_file = True
	except Exception:
		_can_write_log_file = False

# Compose logging configuration with safe fallback to console-only
_handlers = {
	'console': {
		'level': 'INFO',
		'class': 'logging.StreamHandler',
		'formatter': 'simple',
	}
}

if _can_write_log_file:
	_handlers['file'] = {
		'level': 'INFO',
		'class': 'logging.handlers.TimedRotatingFileHandler',
		'filename': str(_log_file_path),
		'formatter': 'verbose',
		'when': 'midnight',
		'interval': 1,
		'backupCount': LOG_RETENTION_DAYS,
		'utc': True,
		'encoding': 'utf-8',
	}

_root_handlers = ['console'] + (['file'] if 'file' in _handlers else [])

LOGGING = {
	'version': 1,
	'disable_existing_loggers': False,
	'formatters': {
		'verbose': {
			'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
			'style': '{',
		},
		'simple': {
			'format': '{levelname} {message}',
			'style': '{',
		},
	},
	'handlers': _handlers,
	'root': {
		'handlers': _root_handlers,
		'level': 'INFO',
	},
	'loggers': {
		'django': {
			'handlers': _root_handlers,
			'level': 'INFO',
			'propagate': False,
		},
		'core': {
			'handlers': _root_handlers,
			'level': 'INFO',
			'propagate': False,
		},
	},
}
